"use client";

import { useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import ProjectCard from "../MiniComponents/ProjectCard";
import { ArrowUpRight } from "lucide-react";
gsap.registerPlugin(ScrollTrigger);

const projects = [
  {
    name: "Rune",
    description:
      "🚀 Rune is your all-in-one productivity toolkit featuring 145+ powerful tools for learning, creating, and working smarter. From text & writing tools, PDF management, image editing, video processing, to developer utilities, calculators, and AI-powered assistants—Rune empowers students, professionals, and creators with free 24/7 access to streamline their workflow.",
    highlights: [
      "145+ free tools including text editors, PDF converters, and image processors",
      "AI-powered tools for writing, summarizing, and content creation",
      "Developer utilities with JSON formatter, regex tester, and code tools",
    ],
    tags: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Rune's AI",
      "Framer Motion",
      "Node.js",
      "Vercel",
    ],
    accent: "0 84% 55%",
    // mobile1: runeM1,
    // mobile2: runeM2,
    // desktop: runeD,
  },
  {
    name: "RuneHub",
    description:
      "🚀 RuneHub is an interactive coding playground that turns programming tutorials into hands-on, AI-guided lessons. Learn JavaScript, Python, and web fundamentals through bite-sized chapters, in-browser execution, and instant feedback that keeps you in the flow.",
    highlights: [
      "Interactive in-browser code editor with instant execution",
      "AI tutor that explains concepts and debugs your code in real time",
      "Structured roadmaps spanning beginner to advanced topics",
    ],
    tags: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Rune's AI",
      "Framer Motion",
    ],
    accent: "220 90% 55%",
    // mobile1: hubM1,
    // mobile2: hubM2,
    // desktop: hubD,
  },
  {
    name: "RuneLearn",
    description:
      "🚀 RuneLearn is the ultimate AI-powered study companion that dynamically generates quizzes, intelligent flashcards, personalized roadmaps, and instantly resolves doubts with its deep-context advanced doubt solver. Designed to turbocharge long-term memory and retention effortlessly.",
    highlights: [
      "Interactive Quizzes and Flashcards dynamically generated by AI",
      "Personalized Learning Roadmaps tailored to your study goals",
      "Advanced Doubt Solver providing in-depth explanations instantly",
    ],
    tags: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Rune's AI"],
    accent: "22 95% 55%",
    // mobile1: learnM1,
    // mobile2: learnM2,
    // desktop: learnD,
  },
];

export default function WorkShowcase() {
  const containerRef = useRef<HTMLDivElement>(null);
  const trackRef = useRef<HTMLDivElement>(null);
  const [activeIdx, setActiveIdx] = useState(0);
  const [progress, setProgress] = useState(0);

  useGSAP(
    () => {
      const panels = gsap.utils.toArray<HTMLElement>(".project-panel");
      if (!trackRef.current || panels.length === 0) return;

      const ctx = gsap.to(trackRef.current, {
        x: () => -(trackRef.current!.scrollWidth - window.innerWidth),
        ease: "none",
        scrollTrigger: {
          trigger: containerRef.current,
          pin: true,
          scrub: 1,
          anticipatePin: 1,
          end: () => "+=" + (trackRef.current!.scrollWidth - window.innerWidth),
          onUpdate: (self) => {
            setProgress(self.progress);
            const idx = Math.round(self.progress * (panels.length - 1));
            setActiveIdx(idx);
          },
          invalidateOnRefresh: true,
        },
      });

      return () => {
        ctx.scrollTrigger?.kill();
      };
    },
    { scope: containerRef },
  );

  return (
    <div className="relative bg-background">
      {/* HERO above */}
      <section className="relative h-[70vh] flex flex-col items-center justify-center overflow-hidden">
        <div
          className="absolute inset-0 bg-radial-glow pointer-events-none"
          aria-hidden
        />
        <div
          className="absolute inset-0 bg-grid-faint opacity-40 pointer-events-none"
          aria-hidden
        />
        <p className="relative tracking-[0.4em] text-[11px] font-medium text-muted-foreground uppercase">
          Crafting Modern Experiences
        </p>
        <h1 className="relative mt-5 text-6xl md:text-8xl lg:text-[10rem] font-black tracking-tighter leading-none text-center">
          <span className="text-foreground">VENTURE</span>
          <br />
          <span className="italic text-gradient-showcase">SHOWCASE</span>
        </h1>
        <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2">
          <span className="text-[10px] tracking-[0.4em] uppercase text-muted-foreground">
            Scroll
          </span>
          <div className="h-10 w-px bg-linear-to-b from-foreground/60 to-transparent" />
        </div>
      </section>

      {/* PINNED HORIZONTAL */}
      <div ref={containerRef} className="relative h-screen overflow-hidden">
        {/* Top HUD */}
        <div className="absolute top-6 left-0 right-0 z-30 px-6 lg:px-16 flex items-center justify-between pointer-events-none">
          <div className="text-[11px] tracking-[0.35em] uppercase text-muted-foreground">
            Selected Work / 2024 — 25
          </div>
          <div className="flex items-center gap-4">
            {projects.map((p, i) => (
              <div key={p.name} className="flex items-center gap-2">
                <span
                  className="h-1.5 w-1.5 rounded-full transition-all"
                  style={{
                    background:
                      i === activeIdx
                        ? `hsl(${p.accent})`
                        : "hsl(var(--muted-foreground) / 0.4)",
                    boxShadow:
                      i === activeIdx ? `0 0 12px hsl(${p.accent})` : "none",
                  }}
                />
                <span
                  className={`text-[11px] tracking-[0.2em] uppercase transition ${
                    i === activeIdx
                      ? "text-foreground"
                      : "text-muted-foreground/50"
                  }`}
                >
                  {p.name}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Big index counter */}
        <div className="absolute right-6 lg:right-16 bottom-10 z-30 pointer-events-none flex items-end gap-2">
          <span className="text-[10rem] leading-[0.8] font-black tracking-tighter text-foreground/[0.06]">
            0{activeIdx + 1}
          </span>
          <span className="text-xs tracking-[0.3em] uppercase text-muted-foreground pb-3">
            / 0{projects.length}
          </span>
        </div>

        {/* Progress bar */}
        <div className="absolute bottom-0 left-0 right-0 h-[2px] bg-border/60 z-30">
          <div
            className="h-full transition-[width] duration-100"
            style={{
              width: `${progress * 100}%`,
              background: `linear-gradient(90deg, hsl(220 95% 65%), hsl(280 90% 65%), hsl(320 95% 65%))`,
            }}
          />
        </div>

        {/* Track */}
        <div ref={trackRef} className="flex h-full will-change-transform">
          {projects.map((p, i) => (
            <ProjectCard key={p.name} project={p} index={i} />
          ))}

          <section className="project-panel relative shrink-0 w-screen h-screen flex flex-col items-center justify-center px-6">
            <div
              className="absolute inset-0 bg-radial-glow pointer-events-none"
              aria-hidden
            />
            <p className="text-[11px] tracking-[0.4em] uppercase text-muted-foreground">
              End of selection
            </p>
            <h3 className="mt-4 text-5xl md:text-7xl font-black tracking-tighter text-center">
              Want to build{" "}
              <span className="italic text-gradient-showcase">
                something next?
              </span>
            </h3>
            <a
              href="#contact"
              className="mt-10 group inline-flex items-center gap-3 px-8 py-4 rounded-full bg-foreground text-background text-sm font-semibold tracking-wide hover:scale-105 transition-transform"
            >
              Start a project
              <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
            </a>
          </section>
        </div>
      </div>
    </div>
  );
}
